### PR TITLE
Create qa workspace

### PR DESCRIPTION
**Pull request by MacTynow**

### CODE REVIEW

**Comment by MacTynow** [comment]
atlantis help

**Comment by AliGrab** [comment]
```cmake
atlantis - Terraform collaboration tool that enables you to collaborate on infrastructure
safely and securely.

Usage: atlantis <command> [workspace] [--verbose]

Commands:
plan           Runs 'terraform plan' on the files changed in the pull request
apply          Runs 'terraform apply' using the plans generated by 'atlantis plan'
help           Get help

Examples:

# Generates a plan for staging workspace
atlantis plan staging

# Generates a plan for a standalone terraform project
atlantis plan

# Applies a plan for staging workspace
atlantis apply staging

# Applies a plan for a standalone terraform project
atlantis apply

**Comment by MacTynow** [comment]
atlantis plan

**Comment by AliGrab** [comment]
**Plan Failed**: This project is currently locked by #2. The locking plan must be applied or discarded before future plans can execute.

**Comment by MacTynow** [comment]
atlantis plan

**Comment by AliGrab** [comment]
**Plan Error**
```
chdir /home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/qa: no such file or directory: running "sh -c terraform init -no-color" in "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/qa": 

```

**Comment by MacTynow** [comment]
atlantis apply

**Comment by AliGrab** [comment]
**Apply Failed**: Pull request must be approved before running apply.

**Comment by MacTynow** [comment]
atlantis plan qa

**Comment by AliGrab** [comment]
**Plan Failed**: No Terraform files were modified.

**Comment by MacTynow** [comment]
atlantis plan

**Comment by AliGrab** [comment]
**Plan Failed**: No Terraform files were modified.

**Comment by MacTynow** [comment]
atlantis plan qa

**Comment by AliGrab** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ module.ec2_etcd.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>

  + module.ec2_test.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/qa/qa/qa.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/qa/qa/qa.tfplan"


```

* To **discard** this plan click [here](http://13.250.49.130:4141/events/lock?id=AliGrab%252Fatlantis-example%252Fqa%252Fqa).

**Comment by AliGrab** [comment]
atlantis plan

**Comment by AliGrab** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ module.ec2_etcd.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>

  + module.ec2_test.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/qa/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/qa/default.tfplan"


```

* To **discard** this plan click [here](http://13.250.49.130:4141/events/lock?id=AliGrab%252Fatlantis-example%252Fqa%252Fdefault).

**Comment by AliGrab** [comment]
atlantis plan

**Comment by AliGrab** [comment]
Ran Plan in 3 directories:
 * `prod`
 * `qa`
 * `staging`

## prod/
**Plan Error**
```
exit status 1: running "sh -c terraform init -no-color" in "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/prod": 
Initializing modules...
- module.ec2_etcd
  Getting source "../aws/ec2"
- module.ec2_test  
  Getting source "../aws/ec2"
Error getting plugins: module "ec2_test  ": module name must be a letter or underscore followed by only letters, numbers, dashes, and underscores

```

---
## qa/
**Plan Error**
```
exit status 1: running "sh -c terraform init -no-color" in "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/qa": 
Initializing modules...
- module.ec2_etcd
  Getting source "../aws/ec2"
- module.ec2_test  
  Getting source "../aws/ec2"
Error getting plugins: module "ec2_test  ": module name must be a letter or underscore followed by only letters, numbers, dashes, and underscores

```

---
## staging/
**Plan Error**
```
exit status 1: running "sh -c terraform init -no-color" in "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/staging": 
Initializing modules...
- module.ec2_etcd
  Getting source "../aws/ec2"
- module.ec2_test  
  Getting source "../aws/ec2"
Error getting plugins: module "ec2_test  ": module name must be a letter or underscore followed by only letters, numbers, dashes, and underscores

```

---

**Comment by AliGrab** [comment]
atlantis plan

**Comment by AliGrab** [comment]
Ran Plan in 3 directories:
 * `prod`
 * `qa`
 * `staging`

## prod/
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ module.ec2_etcd.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>

  + module.ec2_test.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/prod/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/prod/default.tfplan"


```

* To **discard** this plan click [here](http://13.250.49.130:4141/events/lock?id=AliGrab%252Fatlantis-example%252Fprod%252Fdefault).
---
## qa/
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ module.ec2_etcd.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>

  + module.ec2_test.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/qa/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/qa/default.tfplan"


```

* To **discard** this plan click [here](http://13.250.49.130:4141/events/lock?id=AliGrab%252Fatlantis-example%252Fqa%252Fdefault).
---
## staging/
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ module.ec2_etcd.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>

  + module.ec2_test.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/staging/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/default/staging/default.tfplan"


```

* To **discard** this plan click [here](http://13.250.49.130:4141/events/lock?id=AliGrab%252Fatlantis-example%252Fstaging%252Fdefault).
---

**Comment by AliGrab** [comment]
atlantis plan staging

**Comment by AliGrab** [comment]
Ran Plan in 3 directories:
 * `prod`
 * `qa`
 * `staging`

## prod/
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ module.ec2_etcd.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>

  + module.ec2_test.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/staging/prod/staging.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/staging/prod/staging.tfplan"


```

* To **discard** this plan click [here](http://13.250.49.130:4141/events/lock?id=AliGrab%252Fatlantis-example%252Fprod%252Fstaging).
---
## qa/
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ module.ec2_etcd.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>

  + module.ec2_test.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/staging/qa/staging.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/staging/qa/staging.tfplan"


```

* To **discard** this plan click [here](http://13.250.49.130:4141/events/lock?id=AliGrab%252Fatlantis-example%252Fqa%252Fstaging).
---
## staging/
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ module.ec2_etcd.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>

  + module.ec2_test.aws_instance.ec2
      id:                           <computed>
      ami:                          "ami-10acfb73"
      associate_public_ip_address:  "false"
      availability_zone:            <computed>
      disable_api_termination:      "false"
      ebs_optimized:                "false"
      instance_state:               <computed>
      instance_type:                "t2.micro"
      ipv6_address_count:           "0"
      key_name:                     "key"
      monitoring:                   "false"
      network_interface.#:          <computed>
      network_interface_id:         <computed>
      placement_group:              <computed>
      primary_network_interface_id: <computed>
      private_dns:                  <computed>
      private_ip:                   <computed>
      public_dns:                   <computed>
      public_ip:                    <computed>
      security_groups.#:            <computed>
      source_dest_check:            "true"
      subnet_id:                    <computed>
      tags.%:                       "1"
      tags.Name:                    "instance"
      tenancy:                      "default"
      user_data:                    "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      volume_tags.%:                <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/staging/staging/staging.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/atlantis/.atlantis/repos/AliGrab/atlantis-example/3/staging/staging/staging.tfplan"


```

* To **discard** this plan click [here](http://13.250.49.130:4141/events/lock?id=AliGrab%252Fatlantis-example%252Fstaging%252Fstaging).
---

**Comment by AliGrab** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- path: `AliGrab/atlantis-example/prod` workspaces: `default`, `staging`
- path: `AliGrab/atlantis-example/qa` workspaces: `default`, `qa`, `staging`
- path: `AliGrab/atlantis-example/staging` workspaces: `default`, `staging`

**Pull request merged**
